### ISSUE TITLE
Invalid buzz.py file in micropython firmware

### ISSUE THREAD

**Issue by xyb** [KittenBot/meowbit-tutorials#1]
The firmware http://cdn.kittenbot.cn/meowbit/meowpy.uf2 in `micropython/micropython快速开始.md` provide a invalid buzz.py file which can not be imported:

```
MicroPython v1.9.4-616-g41fb4d3-dirty on 2019-03-13; MEOWBIT with STM32F401xE
Type "help()" for more information.
>>> import os
>>> os.listdir()
['unicode12.bin', 'boot.py', 'main.py', 'mpu6050.py', 'buzz.py', '.fseventsd', 'meowbit_unicode.py', '._meowbit_unicode.py']
>>> import buzz
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "buzz.py", line 1, in <module>
NameError: name '������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������' isn't defined
```

**Comment by xmeow** [comment]
The file is already corrected, try delete and it will regenerate on next power on cycle. It could take a while to flush thumb disk cache to spiflash, don't unplug or reset the device while the wring LED is flashing.

**Comment by xmeow** [comment]
Or you can download https://github.com/KittenBot/micropython_meowbit/blob/uf2/examples/meowbit/buzz.py and save to meowbit.
